language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "pypy"

virtualenv:
  system_site_packages: true
  
before_install:
  - sudo apt-get install -qq iverilog
  - sudo apt-get install -qq python-numpy 
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-matplotlib

install:
  - pip install Pillow
  - chmod +x ./scripts/ci/install_myhdl.sh
  - ./scripts/ci/install_myhdl.sh
  
script:
  - cd examples
  - py.test -s 

notifications:
  email: true
