// File: mm_cnt.v
// Generated by MyHDL 1.0dev
// Date: Thu Feb 18 14:58:41 2016


`timescale 1ns/10ps

module mm_cnt (
    clock,
    reset,
    out
);


input clock;
input reset;
output [4:0] out;
wire [4:0] out;

reg [4:0] counter;





always @(posedge clock, negedge reset) begin: MM_CNT_BEH
    if (reset == 0) begin
        counter <= 0;
    end
    else begin
        if ((counter <= 30)) begin
            counter <= (counter + 1);
        end
        else begin
            counter <= (counter - 1);
        end
    end
end



assign out = counter;

endmodule
