// File: mm_gcd.v
// Generated by MyHDL 0.9dev
// Date: Fri Mar 28 21:42:57 2014


`timescale 1ns/10ps

module mm_gcd (
    clock,
    reset,
    a,
    b,
    c,
    start,
    finished
);


input clock;
input reset;
input [31:0] a;
input [31:0] b;
output [31:0] c;
reg [31:0] c;
input start;
output finished;
reg finished;

reg [31:0] y;
reg [31:0] x;





always @(posedge clock) begin: MM_GCD_RTL
    if (reset == 0) begin
        y <= 0;
        x <= 0;
        finished <= 1;
        c <= 0;
    end
    else begin
        if (start) begin
            finished <= 1'b0;
            x <= a;
            y <= b;
        end
        else begin
            if ((y == 0)) begin
                finished <= 1'b1;
                c <= x;
            end
            else if ((x > y)) begin
                x <= (x - y);
            end
            else begin
                y <= (y - x);
            end
        end
    end
end

endmodule
