// File: mm_maths1.v
// Generated by MyHDL 0.9dev
// Date: Fri Mar 28 21:35:46 2014


`timescale 1ns/10ps

module mm_maths1 (
    x,
    y,
    v
);


input signed [15:0] x;
input signed [15:0] y;
output signed [15:0] v;
wire signed [15:0] v;







assign v = ((x + y) * 10);

endmodule
