//
// Generated by Bluespec Compiler, version 2013.12.beta1 (build 32746, 2013-12-02)
//
// On Thu Feb 27 22:22:33 CST 2014
//
//
// Ports:
// Name                         I/O  size props
// RDY_start                      O     1
// result                         O    32 reg
// RDY_result                     O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// start_a                        I    32
// start_b                        I    32
// EN_start                       I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkGCD(CLK,
	     RST_N,

	     start_a,
	     start_b,
	     EN_start,
	     RDY_start,

	     result,
	     RDY_result);
  input  CLK;
  input  RST_N;

  // action method start
  input  [31 : 0] start_a;
  input  [31 : 0] start_b;
  input  EN_start;
  output RDY_start;

  // value method result
  output [31 : 0] result;
  output RDY_result;

  // signals for module outputs
  wire [31 : 0] result;
  wire RDY_result, RDY_start;

  // register x
  reg [31 : 0] x;
  wire [31 : 0] x$D_IN;
  wire x$EN;

  // register y
  reg [31 : 0] y;
  wire [31 : 0] y$D_IN;
  wire y$EN;

  // inputs to muxes for submodule ports
  wire [31 : 0] MUX_x$write_1__VAL_2, MUX_y$write_1__VAL_2;

  // remaining internal signals
  wire x_ULE_y___d3;

  // action method start
  assign RDY_start = y == 32'd0 ;

  // value method result
  assign result = x ;
  assign RDY_result = y == 32'd0 ;

  // inputs to muxes for submodule ports
  assign MUX_x$write_1__VAL_2 = x - y ;
  assign MUX_y$write_1__VAL_2 = y - x ;

  // register x
  assign x$D_IN = EN_start ? start_a : MUX_x$write_1__VAL_2 ;
  assign x$EN = EN_start || !x_ULE_y___d3 && y != 32'd0 ;

  // register y
  assign y$D_IN = EN_start ? start_b : MUX_y$write_1__VAL_2 ;
  assign y$EN = EN_start || x_ULE_y___d3 && y != 32'd0 ;

  // remaining internal signals
  assign x_ULE_y___d3 = x <= y ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        x <= `BSV_ASSIGNMENT_DELAY 32'd0;
	y <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (x$EN) x <= `BSV_ASSIGNMENT_DELAY x$D_IN;
	if (y$EN) y <= `BSV_ASSIGNMENT_DELAY y$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    x = 32'hAAAAAAAA;
    y = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkGCD

